### ISSUE TITLE
App won't start without http2

### ISSUE THREAD

**Issue by justinmc** [Daplie/letsencrypt-express#26]
The project seems to depend on http2 without listing it in its dependencies.  Is this an accidental include of http2 or should it be included in package.json?

You can reproduce this by installing letsencrypt-express and requiring it, then trying to start your server.  It won't start because http2 wasn't found.

A quick workaround is just to install http2 into your app, but this is obviously not ideal.

**Comment by coolaj86** [comment]
The demo depends on http2, but the actual use case does not.

The "standalone" and "express" examples are kinda just for "ooh, check and see that it works, but the raw http/https examples are the important ones" I'd prefer to not even have the "standalone" example, but for some reason people are drawn to "this only takes 6 lines of code instead of 10".

Since both `http2` and `spdy` are popular http2 modules I don't want to add it to the deps when the end user may use something different.

As a compromise I added `npm install http2 --save` to the README.

What do you think about that as a solution?

**Comment by justinmc** [comment]
That sounds perfect to me, thanks for the thorough explanation :+1:
