### ISSUE TITLE
Instructions for use on AWS ElasticBeanstalk

### ISSUE THREAD

**Issue by DannyBrown** [Daplie/letsencrypt-express#36]
Hi,

I love the easy of use of this module, thanks for making it available.

I have something which appears to work locally, however I am having no luck it getting it to work on AWS Elastic Beanstalk.

The code can be found here:
https://github.com/csblogs/api-server/blob/add/basic-security/src/server.js

I feel like I'm not understanding what I have to do on the Elastic Loadbalancer side of things to get this working. Do you have any experience with this and could point me in the right direction? 

Thanks again 😄 
Danny

**Comment by coolaj86** [comment]
I haven't used elastic beanstalk, but I know of a couple of things to check on:

* usage rate limits https://community.letsencrypt.org/t/rate-limits-for-lets-encrypt/6769
  * have you, in your testing, exhausted the number of certificates that can be issued?
  * per domain?
  * per ip address?
  * per account?

Does elastic beanstalk share that same ip address with many other hosts?

Does elastic beanstalk correctly report `req.headers.host`?

Have you correctly configured express with `app.set("trust proxy", ...)`? (see http://expressjs.com/en/guide/behind-proxies.html)

I believe that beanstalk instances are ephemeral, correct? If so, you will need to store the certificates in a database rather than on disk (otherwise you'll hit the rate limits very regularly) and we would need to modify the `letiny-core` and `node-letsencrypt` dependencies in order to do that. That's something that's totally in the roadmap, but not in the "between next week and next month" roadmap.

If you need that feature I can arrange to get it on the near-future roadmap by offering my services as a consultant at an hourly or project rate, but as a company we don't have the resources right now to dedicate to that feature.

**Comment by DannyBrown** [comment]
Ah ok, seems like it won't be possible then :)

CSB is just an open source project so wouldn't have budget for your services. Thank you though :)

**Comment by coolaj86** [comment]
I'm going to open this back up because it's an important issue.

Also, I can show you the code points that need to change to get done what you need to get done and help answer questions if you'd like to create a fork and implement the changes. I want to say there are only about 4 function calls that need to be abstracted and have code that connects to a DB put in their place, plus an additional options parameter to specify the storage being file or DB.

**Comment by tony-gutierrez** [comment]
Heres a way to install certs on single instance elastic beanstalk node servers: http://bluefletch.com/blog/domain-agnostic-letsencrypt-ssl-config-for-elastic-beanstalk-single-instances/

**Comment by coolaj86** [comment]
Moving this discussion to https://github.com/Daplie/letsencrypt-express/issues/36. Once the config is abstracted such that it can be saved in a database this will be solved for.
