### ISSUE TITLE
HTTP requests to HTTPS port hang

### ISSUE THREAD

**Issue by tremby** [Daplie/letsencrypt-express#46]
I'm not sure if this is a bug in letsencrypt-express or elsewhere (Express or my own code) but I noticed that HTTP requests to the port letsencrypt-express is listening for HTTPS requests on seem to hang forever. I'm not sure if this is expected or an issue. I worry that it may keep resources tied up while the connection remains open.

**Comment by coolaj86** [comment]
I'm not sure what you mean by this.

The webserver always remains listening. Any request through the LE middleware is just for a challenge file and will be handled much in the same way a normal static file would.

Perhaps there is something in your own middleware that is not handling a response?

**Comment by tremby** [comment]
Maybe I'm not understanding something fundamental here. I was under the impression letsencrypt-express worked more like a proxy than a middleware. When I configure middlewares I do so with `app.use(middleware)`, but I add letsencrypt-express by no longer telling my app to listen on a particular port, but instead passing the app as a handler to letsencrypt-express, which does the listening and passes the requests it won't handle itself through to my app.

Am I misunderstanding?

Anyway, when I send an HTTP request to the HTTPS port I get no response though the connection remains open. I would have expected an error message or just for the connection to be closed. But I take it you're saying that's something I need to set up as part of my app?

**Comment by coolaj86** [comment]
No, it's not a proxy. It's an SNICallback handler and an http middleware.

Most people fundamentally misunderstand the express and http modules because they examples you see in the dumbed-down tutorials strip out the http stuff to save about 2 lines of code.

```javascript
// bad idea
app = express();
app.listen(port);

// good idea
app = express();
server = https.createServer(app);
server.listen(port, cb);
```

But since we need to pass special options directly to the https server, we can't use express' shortcut method.

Try whatever your app is doing using the http modules raw and after you've got that working then we can see if there's a problem with letsencrypt-express, but I don't think that there is.

Closing for now since this is probably not letsencrypt-express related, but feel free to carry on the conversation here.
