### ISSUE TITLE
Update Setup documentation for certbot/certbot-auto - configDir is incorrect

### ISSUE THREAD

**Issue by bartread** [Daplie/letsencrypt-express#50]
If I follow the instructions at https://letsencrypt.org/getting-started/ to install letsencrypt (now certbot) using certbot-auto on a bitnami Ubuntu instance, the folder mentioned in the Setup section of the docs as the configDir simply doesn't exist. I doubt the OS makes any difference - I suspect I'd see something similar on OSX were I to use certbot-auto.

In fact it's not clear at all where letsencrypt configuration now lives, having had a quick look through the folder hierarchy, which makes this a bit of a blocker.

Here's the offending section:

```
'use strict';

/* Note: using staging server url, remove .testing() for production
Using .testing() will overwrite the debug flag with true */ 
var LEX = require('letsencrypt-express').testing();

var lex = LEX.create({
  configDir: require('os').homedir() + '/letsencrypt/etc' // THIS FOLDER DOESN'T EXIST
, approveRegistration: function (hostname, cb) { // leave `null` to disable automatic registration
    // Note: this is the place to check your database to get the user associated with this domain
    cb(null, {
      domains: [hostname]
    , email: 'CHANGE_ME' // user@example.com
    , agreeTos: true
    });
  }
});
```

As I say, the configDir folder just doesn't exist, nor does anything similar exist under /etc/letsencrypt.

**Comment by jskrzypek** [comment]
when certbot/letsencrypt is run, it's supposed be either run
 * with `sudo`, allowing it to create `/etc/letsencrypt` and the other `/var/...` dirs that it wants to on it's own since it's running as root
*or*
 * not sudo, using the options like `--config-dir` to modify user-land directories and avoid the requirement to use `sudo` (go to [the cli docs](https://certbot.eff.org/docs/using.html#command-line-options) and scroll down to `paths` to see the complete list of paths you can override)

This means that when run `configDir: require('os').homedir() + '/letsencrypt/etc'` (which is the default) the module puts the certs created under the home directory. You probably don't see it yet because it hasn't been created, something you can just let it do when it runs.

**Comment by jskrzypek** [comment]
Also if you're looking for the config directory created by running `certbot-auto` as separate from the commands executed by this module, that's probably available at `/etc/letsencrypt`.

**Comment by coolaj86** [comment]
What is the action that you want me to take on this?

To update the README.md to include information about how users should set `configDir` to `/etc/letsencrypt` in production? And that the folder will be created if it doesn't exist?

**Comment by coolaj86** [comment]
Since I haven't heard back from you and I'm not sure what exactly the suggestion is, I'm closing the issue.
