### ISSUE TITLE
http01Port doesn't seem to get passed on

### ISSUE THREAD

**Issue by n3pal** [Daplie/letsencrypt-express#69]
Hey, 

Love the package, I have a small issue. My apps aren't exposing port 80 to pass the security challenge for http01. I've read that a http-01-port can be passed in, I've tried a couple of different configs but none seemed to be working. 

Something like this:

```javascript
var lex = LEX.create({
  configDir: require('os').homedir() + '/letsencrypt/etc',
  http01Port: 8080,
, approveRegistration: function (hostname, approve) { // leave `null` to disable automatic registration
    if (hostname === DOMAIN) { // Or check a database or list of allowed domains
      approve(null, {
        domains: [DOMAIN]
      , email: EMAIL
      , agreeTos: true
      });
    }
  }
});
```

Did however change the value in the renew/*.config file, but didn't use the http01Port for the actual challenge. If I open up port 80 and route it to my app, the challenge gets passed, otherwise the http-01 challenge gets the 'failed' status.

Is there something that I'm missing here, a different way to pass in the http01Port or is it just not possible at the moment? 

Thanks for your help!

**Comment by coolaj86** [comment]
That option is for if you have a local proxy like nginx of if you're using a non-standard cert server.

It only affects the client, not the server.

I'll keep this open until I make better note of that in the docs (or you can make a PR).

**Comment by n3pal** [comment]
Thank you for the reply, would passing the http01port be doable with the -cli version of the package?

**Comment by coolaj86** [comment]
`http01port` refers to which port you are listening on:

```
var plainServer = http.createServer(function (req, res) {
  req.end("Hello, World!");
});
plainServer.listen(http01port, function () {
  console.info("Ready to serve you from port", plainServer.address().port);
});
```

You cannot inform the server of which port you would like it to talk to you. It will only support 80 for http-01 and 443 for tls-sni-01.

However, there's also a dns-01 challenge, which is supported with [letsencrypt-cli](https://github.com/Daplie/letsencrypt-cli) if you use `--manual` and it requires updating DNS records rather than using a port.

If you look at https://github.com/Daplie/le-acme-core/issues/9 and the guy links to some pretty simple coffeescript that does it and shouldn't be too hard to turn back into JavaScript.
