### ISSUE TITLE
Migration to v2.x not very clear

### ISSUE THREAD

**Issue by jacargentina** [Daplie/letsencrypt-express#76]
I was using previous version 1.x and now i've updated it to 2.x.

Before i was able to get the started http(s) server from the `listen` callback. How can i do that now?

**Comment by coolaj86** [comment]
The behavior should have stayed the same (https://github.com/Daplie/letsencrypt-express/blob/master/lex.js#L52). However, don't even bother using `.listen()`.

You're only saving, literally, 3 lines of code. I absolutely hate the anti-pattern of having frameworks including `.listen()` wrappers, but people love seeing "fewer lines of code", so I did it just like everyone else does so that I don't scare away the people that get anxiety over seeing more than one `require()` in an example... sadness...

However, if you look at the **Usage** example right below you'll see this:

```javascript
// handles acme-challenge and redirects to https
require('http').createServer(le.middleware()).listen(80, function () {
  console.log("Listening for ACME http-01 challenges on", this.address());
});

// handles your app
require('https').createServer(le.httpsOptions, le.middleware(app)).listen(443, function () {
  console.log("Listening for ACME tls-sni-01 challenges and serve app on", this.address());
});
```

I probably could stand to create a migration section.
